# Generated by Django 3.2 on 2022-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinstance',
            name='dayprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
