# Generated by Django 3.2 on 2022-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20220531_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('B', 'Booking'), ('A', 'Available'), ('R', 'Reserved'), ('M', 'Maintenance')], default='a', help_text='Vehicle availability', max_length=1),
        ),
    ]
