# Generated by Django 3.2 on 2022-06-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_alter_rentinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Confirmed'), ('A', 'Available'), ('R', 'Reserved'), ('M', 'Maintenance')], default='a', help_text='Vehicle availability', max_length=1),
        ),
    ]
